### ISSUE TITLE
OTP20 and OTP21

### ISSUE THREAD

**Issue by martinsumner** [martinsumner/leveled#134]
Currently leveled will compile for OTP20 only by disabling warnings as errors.  Once compiled, it appears to show some signs of measurable speed ups.

OTP21 comes with potentially greater enhancements.

Need to find some way of supporting R16 through to OTP21 in the short term.  Either convert gen_fsm to gen_server or to https://gitlab.com/Project-FiFo/gen_fsm_compat

**Comment by bryanhuntesl** [comment]
Pity gen_fsm_compat is on gitlab/hex.

Perhaps fork to github and keep the build consistent?

My confidence in hex dependencies has declined dramatically of late,
particularly given Riak's legacy build tooling.

https://skillsmatter.com/skillscasts/11856-i-m-stealing-api-keys-from-your-site-here-s-how

https://github.com/nietaki/hoplon

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/136
