### ISSUE TITLE
How to break a `book_objectfold`

### ISSUE THREAD

**Issue by dergraf** [martinsumner/leveled#211]
I would like to stop a `book_objectfold` e.g. using a `throw` similar to what is possible in a `book_indexfold` .

Am I missing something or is this currently not possible.

Additional info:
I have a bucket containing objects with a sext encoded key similar to `sext:encode({Prefix::any(), Key::any})` .
I'd like to initiate the fold by providing a range from `sext:encode({Prefix::any(), '_'})` to `<<"$all">>` and stop the fold as soon as I hit a key with a different Prefix.

**Comment by martinsumner** [comment]
The ability to stop via a throw was something I added specifically for riak compatibility, so at the time I added it only where riak needed it.

The support was put in using the wrap_runner/2 function in leveled_runner:

https://github.com/martinsumner/leveled/blob/master/src/leveled_runner.erl#L140-L144

https://github.com/martinsumner/leveled/blob/master/src/leveled_runner.erl#L169-L173

But this isn't in any of the object folding , so stopping through a `throw` isn't possible there right now.  However it should be trivial to add it, and perhaps I should for consistency across all folds.  I had to do it to make Riak work, and at the time I thought it was an ugly approach - but based on the existence of your problem, perhaps it is a generically useful way of allowing the application to control the endpoint of folds.

It might be possible to solve your problem by doing an objectfold over a key range - https://github.com/martinsumner/leveled/blob/master/src/leveled_bookie.erl#L798-L829.  However, I'm not sure how to define the end key in the range in your case, especially as the range is end_key inclusive.

I will think some more overnight, and work on a change tomorrow.  Assuming I don't hit any nasty issues, I will  try and make end through throw possible across all folds.  It seems potentially easier than adding more options in for defining ranges in different scenarios.

**Comment by dergraf** [comment]
Hi Martin, thanks for the prompt and detailed response.

I think it would be great to have it for consistency reasons, however it is ugly, as mentioned. But to my knowledge also Ets folds can only be interrupted by throwing exceptions ;)

What I originally wanted for leveled is to have LevelDB/Rocksb style iterators with a simple iterator interface e.g next,prev,close, but I guess that's more complicated to add.

**Comment by dergraf** [comment]
That's great! Thank you very much! I will test it right away!

Another question: have you considered exposing the `book_mput` API also for non-head bookies?

**Comment by dergraf** [comment]
Solved! Thanks!
