### ISSUE TITLE
book_indexfold and tuple buckets - BLOCKS RELEASE

### ISSUE THREAD

**Issue by martinsumner** [martinsumner/leveled#219]
book_indexfold can be passed a constraint which is either

{Bucket, Key} | Bucket

But what if the bucket is a tuple bucket (as with typed buckets in riak).  book_indexfold cannot tell that the tuple in the constraint is a bucket and not a bucket and a key.

**Comment by russelldb** [comment]
tag the tuple? `{bucket, Bucket::riak_object:bucket()}` `{bucket_key, {ETC, ETC}}`?

**Comment by martinsumner** [comment]
Yes I think so.  I need to broaden the testing of tuple_buckets to make sure this isn't the only case.

**Comment by martinsumner** [comment]
So I did test this, sort of:

https://github.com/martinsumner/leveled/blob/master/test/end_to_end/riak_SUITE.erl#L28

will lead to a book_indexfold:

https://github.com/martinsumner/leveled/blob/master/test/end_to_end/riak_SUITE.erl#L119-L143

However, in this case I've stipulated an empty start key so there is no problem.

When used in Riak, it always passes a StartKey - so again this is safe:

https://github.com/martinsumner/riak_kv/blob/mas-2.2.5-clusteraae/src/riak_kv_leveled_backend.erl#L293-L300

So the answer might be as simple as removing the option for the constraint to be just Bucket.  There's a couple of tests that would change, but nothing else.

**Comment by russelldb** [comment]
+1 on the simple answer

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/221
