### ISSUE TITLE
What if riak_object in term_to_binary

### ISSUE THREAD

**Issue by ramensen** [martinsumner/leveled#263]
In riak leveled may receive an object handed off in this form:

```<<131,104,7,100,0,8,114,95,111,98,106,101,99,116,109,0,0,0,9,101,112,115,82,101,99,111,114,100,109,0,0,0,19,69,70,56,68,67,55,45,90,70,52,66,49,69,45,49,49,69,56,65,108,0,0,0,1,104,3,100,0,9,114,95,99,111,110,116,101,110,116,104,9,100,0,4,100,105,99,116,97,7,97,16,97,16,97,8,97,80,97,48,104,16,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,104,1,104,16,106,106,108,0,0,0,1,108,0,0,0,1,109,0,0,0,5,76,105,110,107,115,106,106,106,108,0,0,0,1,108,0,0,0,1,109,0,0,0,3,100,111,116,104,2,109,0,0,0,8,26,182,168,146,110,67,57,69,104,2,97,1,110,5,0,17,203,5,213,14,106,106,106,106,106,106,108,0,0,0,2,108,0,0,0,17,109,0,0,0,12,99,111,110,116,101,110,116,45,116,121,112,101,97,97,97,112,97,112,97,108,97,105,97,99,97,97,97,116,97,105,97,111,97,110,97,47,97,106,97,115,97,111,97,110,106,108,0,0,0,23,109,0,0,0,11,88,45,82,105,97,107,45,86,84,97,103,97,51,97,112,97,83,97,85,97,110,97,72,97,120,97,108,97,111,97,117,97,49,97,54,97,82,97,118,97,116,97,85,97,89,97,117,97,115,97,116,97,89,97,90,106,106,108,0,0,0,1,108,0,0,0,14,109,0,0,0,5,105,110,100,101,120,104,2,109,0,0,0,9,100,101,108,116,97,95,98,105,110,109,0,0,0,16,50,48,49,56,48,57,48,54,49,54,48,48,49,55,124,49,104,2,109,0,0,0,17,100,105,115,112,101,110,115,101,114,100,97,116,101,95,98,105,110,109,0,0,0,28,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,24,100,105,115,112,101,110,115,105,110,103,115,105,116,101,115,116,97,116,117,115,95,98,105,110,109,0,0,0,10,70,80,50,51,48,95,48,48,48,49,104,2,109,0,0,0,19,110,101,120,116,97,99,116,105,118,105,116,121,110,97,100,95,98,105,110,109,0,0,0,15,101,120,112,105,114,101,95,50,48,49,57,48,51,48,54,104,2,109,0,0,0,13,110,104,115,110,117,109,98,101,114,95,98,105,110,109,0,0,0,10,57,52,48,51,53,57,56,53,49,52,104,2,109,0,0,0,17,110,104,115,110,117,109,98,101,114,100,97,116,101,95,98,105,110,109,0,0,0,33,57,52,48,51,53,57,56,53,49,52,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,26,110,104,115,110,117,109,98,101,114,100,105,115,112,101,110,115,101,114,100,97,116,101,95,98,105,110,109,0,0,0,39,57,52,48,51,53,57,56,53,49,52,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,26,110,104,115,110,117,109,98,101,114,112,114,101,115,99,100,105,115,112,100,97,116,101,95,98,105,110,109,0,0,0,46,57,52,48,51,53,57,56,53,49,52,124,89,57,48,51,52,55,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,27,110,104,115,110,117,109,98,101,114,112,114,101,115,99,114,105,98,101,114,100,97,116,101,95,98,105,110,109,0,0,0,40,57,52,48,51,53,57,56,53,49,52,124,89,57,48,51,52,55,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,18,110,111,109,112,104,97,114,109,115,116,97,116,117,115,95,98,105,110,109,0,0,0,10,70,80,50,51,48,95,48,48,48,49,104,2,109,0,0,0,17,112,114,101,115,99,100,105,115,112,100,97,116,101,95,98,105,110,109,0,0,0,35,89,57,48,51,52,55,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,18,112,114,101,115,99,114,105,98,101,114,100,97,116,101,95,98,105,110,109,0,0,0,29,89,57,48,51,52,55,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,104,2,109,0,0,0,25,112,114,101,115,99,114,105,98,105,110,103,115,105,116,101,115,116,97,116,117,115,95,98,105,110,109,0,0,0,11,89,57,48,51,52,55,95,48,48,48,49,106,106,106,108,0,0,0,1,108,0,0,0,1,109,0,0,0,20,88,45,82,105,97,107,45,76,97,115,116,45,77,111,100,105,102,105,101,100,104,3,98,0,0,6,0,98,0,3,207,17,98,0,6,218,82,106,106,108,0,0,0,1,108,0,0,0,2,109,0,0,0,11,88,45,82,105,97,107,45,77,101,116,97,104,2,107,0,23,88,45,82,105,97,107,45,77,101,116,97,45,82,101,99,111,114,100,45,84,121,112,101,107,0,5,65,99,117,116,101,106,106,109,0,0,19,0,123,34,100,111,99,117,109,101,110,116,115,34,58,32,91,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,51,56,53,56,50,57,95,50,68,50,69,68,70,95,49,52,54,50,57,48,50,55,54,53,34,93,44,32,34,112,97,116,105,101,110,116,34,58,32,123,34,103,105,118,101,110,34,58,32,34,68,79,78,79,84,85,83,69,34,44,32,34,115,117,102,102,105,120,34,58,32,34,34,44,32,34,102,97,109,105,108,121,34,58,32,34,88,88,84,69,83,84,80,65,84,73,69,78,84,84,82,67,69,79,78,69,34,44,32,34,108,111,119,101,114,65,103,101,76,105,109,105,116,34,58,32,102,97,108,115,101,44,32,34,104,105,103,104,101,114,65,103,101,76,105,109,105,116,34,58,32,102,97,108,115,101,44,32,34,112,114,101,102,105,120,34,58,32,34,77,82,34,44,32,34,110,104,115,78,117,109,98,101,114,34,58,32,34,57,52,48,51,53,57,56,53,49,52,34,44,32,34,98,105,114,116,104,84,105,109,101,34,58,32,34,49,57,56,48,48,52,50,48,34,125,44,32,34,99,104,97,110,103,101,76,111,103,34,58,32,123,34,69,70,66,53,51,48,68,50,45,66,49,69,68,45,49,49,69,56,45,65,50,57,48,45,70,48,57,50,49,67,49,48,67,53,66,53,34,58,32,123,34,112,114,101,67,104,97,110,103,101,83,116,97,116,117,115,68,105,99,116,34,58,32,123,125,44,32,34,102,114,111,109,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,116,111,83,116,97,116,117,115,34,58,32,34,48,48,48,49,34,44,32,34,112,111,115,116,67,104,97,110,103,101,83,116,97,116,117,115,68,105,99,116,34,58,32,123,34,105,115,115,117,101,49,34,58,32,123,34,108,105,110,101,73,116,101,109,115,34,58,32,123,34,49,34,58,32,34,48,48,48,55,34,44,32,34,50,34,58,32,34,48,48,48,55,34,125,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,34,58,32,34,48,48,48,49,34,125,125,44,32,34,97,103,101,110,116,80,101,114,115,111,110,34,58,32,34,71,56,52,52,56,56,55,57,34,44,32,34,83,67,78,34,58,32,50,44,32,34,105,110,115,116,97,110,99,101,70,114,111,109,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,97,103,101,110,116,83,121,115,116,101,109,83,68,83,34,58,32,34,50,51,48,56,49,49,50,48,49,50,52,49,34,44,32,34,105,110,115,116,97,110,99,101,34,58,32,34,49,34,44,32,34,112,111,115,116,67,104,97,110,103,101,67,117,114,114,101,110,116,73,115,115,117,101,34,58,32,49,44,32,34,112,114,101,67,104,97,110,103,101,67,117,114,114,101,110,116,73,115,115,117,101,34,58,32,110,117,108,108,44,32,34,97,103,101,110,116,80,101,114,115,111,110,82,111,108,101,34,58,32,34,78,111,116,80,114,111,118,105,100,101,100,34,44,32,34,73,110,116,101,114,110,97,108,73,68,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,51,56,53,56,50,57,95,50,68,50,69,68,70,95,49,52,54,50,57,48,50,55,54,53,34,44,32,34,82,101,115,112,111,110,115,101,32,80,97,114,97,109,101,116,101,114,115,34,58,32,123,34,114,101,115,112,111,110,115,101,84,101,120,116,34,58,32,34,92,34,80,114,101,115,99,114,105,112,116,105,111,110,32,117,112,108,111,97,100,32,115,117,99,99,101,115,115,102,117,108,92,34,34,44,32,34,116,105,109,101,83,116,97,109,112,65,99,107,34,58,32,34,92,34,50,48,49,56,48,57,48,54,84,49,54,48,48,49,55,46,51,56,53,92,34,34,44,32,34,114,101,102,84,111,77,101,115,115,97,103,101,73,68,34,58,32,34,92,34,69,70,66,53,51,48,68,50,45,66,49,69,68,45,49,49,69,56,45,65,50,57,48,45,70,48,57,50,49,67,49,48,67,53,66,53,92,34,34,44,32,34,116,111,65,83,73,68,34,58,32,34,92,34,50,51,48,56,49,49,50,48,49,50,52,49,92,34,34,44,32,34,102,114,111,109,65,83,73,68,34,58,32,34,92,34,57,57,48,49,48,49,50,51,52,53,54,55,92,34,34,44,32,34,115,101,114,118,105,99,101,65,83,73,68,34,58,32,34,92,34,54,49,56,55,50,57,52,54,49,48,51,55,92,34,34,44,32,34,116,105,109,101,83,116,97,109,112,83,101,110,116,34,58,32,34,92,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,92,34,34,44,32,34,118,101,114,115,105,111,110,67,111,100,101,34,58,32,34,92,34,86,51,78,80,102,73,84,52,46,50,46,48,48,92,34,34,44,32,34,114,101,115,112,111,110,115,101,65,99,116,105,111,110,34,58,32,34,92,34,77,67,67,73,95,73,78,48,49,48,48,48,48,85,75,49,51,92,34,34,44,32,34,109,101,115,115,97,103,101,73,68,34,58,32,34,92,34,65,49,65,65,68,49,54,54,45,55,67,55,49,45,52,49,50,49,45,57,56,68,70,45,55,70,48,67,50,53,68,68,66,50,55,50,92,34,34,44,32,34,116,111,80,97,114,116,121,75,101,121,34,58,32,34,92,34,89,69,65,45,48,48,48,48,56,48,54,92,34,34,44,32,34,102,114,111,109,80,97,114,116,121,75,101,121,34,58,32,34,92,34,84,69,83,84,86,49,52,49,45,50,48,49,50,48,53,92,34,34,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,73,68,34,58,32,34,92,34,69,70,56,68,67,55,45,90,70,52,66,49,69,45,49,49,69,56,65,43,92,34,34,44,32,34,114,101,102,84,111,69,118,101,110,116,73,68,34,58,32,34,92,34,54,66,70,52,68,69,68,56,45,56,66,49,66,45,52,69,67,54,45,57,48,51,67,45,67,54,68,66,66,56,70,53,70,51,50,57,92,34,34,125,44,32,34,105,115,115,117,101,115,65,108,116,101,114,101,100,66,121,67,104,97,110,103,101,34,58,32,91,34,49,34,93,44,32,34,83,111,117,114,99,101,32,88,83,76,84,34,58,32,34,114,101,113,117,101,115,116,83,117,99,99,101,115,115,82,101,115,112,111,110,115,101,95,77,67,65,73,95,77,84,48,52,48,49,48,49,85,75,48,51,46,120,115,108,34,44,32,34,105,110,116,101,114,97,99,116,105,111,110,73,68,34,58,32,34,80,79,82,88,95,73,78,48,50,48,49,48,49,85,75,51,49,34,44,32,34,105,110,115,116,97,110,99,101,84,111,83,116,97,116,117,115,34,58,32,34,48,48,48,49,34,44,32,34,97,103,101,110,116,82,111,108,101,80,114,111,102,105,108,101,67,111,100,101,73,100,34,58,32,34,49,48,51,49,52,50,57,57,57,57,56,57,34,44,32,34,84,105,109,101,115,116,97,109,112,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,34,44,32,34,116,105,109,101,80,114,101,112,97,114,101,100,70,111,114,85,112,100,97,116,101,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,79,114,103,67,111,100,101,34,58,32,110,117,108,108,125,125,44,32,34,105,110,100,101,120,101,115,34,58,32,123,34,112,114,101,115,99,114,105,98,105,110,103,83,105,116,101,83,116,97,116,117,115,95,98,105,110,34,58,32,91,34,89,57,48,51,52,55,95,48,48,48,49,34,93,44,32,34,110,101,120,116,65,99,116,105,118,105,116,121,78,65,68,95,98,105,110,34,58,32,91,34,101,120,112,105,114,101,95,50,48,49,57,48,51,48,54,34,93,44,32,34,112,114,101,115,99,68,105,115,112,68,97,116,101,95,98,105,110,34,58,32,91,34,89,57,48,51,52,55,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,110,104,115,78,117,109,98,101,114,80,114,101,115,99,68,105,115,112,68,97,116,101,95,98,105,110,34,58,32,91,34,57,52,48,51,53,57,56,53,49,52,124,89,57,48,51,52,55,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,100,105,115,112,101,110,115,105,110,103,83,105,116,101,83,116,97,116,117,115,95,98,105,110,34,58,32,91,34,70,80,50,51,48,95,48,48,48,49,34,93,44,32,34,110,111,109,80,104,97,114,109,83,116,97,116,117,115,95,98,105,110,34,58,32,91,34,70,80,50,51,48,95,48,48,48,49,34,93,44,32,34,112,114,101,115,99,114,105,98,101,114,68,97,116,101,95,98,105,110,34,58,32,91,34,89,57,48,51,52,55,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,110,104,115,78,117,109,98,101,114,95,98,105,110,34,58,32,91,34,57,52,48,51,53,57,56,53,49,52,34,93,44,32,34,100,101,108,116,97,95,98,105,110,34,58,32,91,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,124,49,34,93,44,32,34,110,104,115,78,117,109,98,101,114,68,97,116,101,95,98,105,110,34,58,32,91,34,57,52,48,51,53,57,56,53,49,52,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,110,104,115,78,117,109,98,101,114,80,114,101,115,99,114,105,98,101,114,68,97,116,101,95,98,105,110,34,58,32,91,34,57,52,48,51,53,57,56,53,49,52,124,89,57,48,51,52,55,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,100,105,115,112,101,110,115,101,114,68,97,116,101,95,98,105,110,34,58,32,91,34,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,44,32,34,110,104,115,78,117,109,98,101,114,68,105,115,112,101,110,115,101,114,68,97,116,101,95,98,105,110,34,58,32,91,34,57,52,48,51,53,57,56,53,49,52,124,70,80,50,51,48,124,50,48,49,56,48,57,48,54,49,54,48,48,49,49,124,82,50,124,48,48,48,49,34,93,125,44,32,34,105,110,115,116,97,110,99,101,115,34,58,32,123,34,49,34,58,32,123,34,99,111,109,112,108,101,116,105,111,110,68,97,116,101,34,58,32,102,97,108,115,101,44,32,34,100,105,115,112,101,110,115,101,72,105,115,116,111,114,121,34,58,32,123,125,44,32,34,110,111,109,105,110,97,116,101,100,68,111,119,110,108,111,97,100,68,97,116,101,34,58,32,102,97,108,115,101,44,32,34,112,114,101,118,105,111,117,115,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,108,97,115,116,68,105,115,112,101,110,115,101,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,112,114,105,111,114,80,114,101,118,105,111,117,115,73,115,115,117,101,68,97,116,101,34,58,32,102,97,108,115,101,44,32,34,99,108,97,105,109,34,58,32,123,34,104,105,115,116,111,114,105,99,67,108,97,105,109,71,85,73,68,115,34,58,32,102,97,108,115,101,44,32,34,99,108,97,105,109,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,104,105,115,116,111,114,105,99,68,105,115,112,101,110,115,101,67,108,97,105,109,77,115,103,82,101,102,34,58,32,102,97,108,115,101,44,32,34,99,108,97,105,109,71,85,73,68,34,58,32,102,97,108,115,101,44,32,34,98,97,116,99,104,73,68,34,58,32,102,97,108,115,101,44,32,34,98,97,116,99,104,78,117,109,98,101,114,34,58,32,102,97,108,115,101,44,32,34,100,105,115,112,101,110,115,101,67,108,97,105,109,77,115,103,82,101,102,34,58,32,102,97,108,115,101,44,32,34,99,108,97,105,109,82,101,98,117,105,108,100,34,58,32,102,97,108,115,101,44,32,34,99,108,97,105,109,82,101,99,101,105,118,101,100,68,97,116,101,34,58,32,102,97,108,115,101,125,44,32,34,100,105,115,112,101,110,115,101,34,58,32,123,34,108,97,115,116,68,105,115,112,101,110,115,101,78,111,116,105,102,105,99,97,116,105,111,110,77,115,103,82,101,102,34,58,32,102,97,108,115,101,44,32,34,100,105,115,112,101,110,115,105,110,103,79,114,103,97,110,105,122,97,116,105,111,110,34,58,32,102,97,108,115,101,44,32,34,108,97,115,116,68,105,115,112,101,110,115,101,68,97,116,101,34,58,32,102,97,108,115,101,44,32,34,108,97,115,116,68,105,115,112,101,110,115,101,78,111,116,105,102,105,99,97,116,105,111,110,71,117,105,100,34,58,32,102,97,108,115,101,125,44,32,34,110,101,120,116,65,99,116,105,118,105,116,121,34,58,32,123,34,100,97,116,101,34,58,32,34,50,48,49,57,48,51,48,54,34,44,32,34,97,99,116,105,118,105,116,121,34,58,32,34,101,120,112,105,114,101,34,125,44,32,34,99,97,110,99,101,108,108,97,116,105,111,110,115,34,58,32,91,93,44,32,34,101,120,112,105,114,121,68,97,116,101,34,58,32,34,50,48,49,57,48,51,48,54,34,44,32,34,100,105,115,112,101,110,115,101,87,105,110,100,111,119,76,111,119,68,97,116,101,34,58,32,34,50,48,49,56,48,57,48,54,34,44,32,34,105,110,115,116,97,110,99,101,78,117,109,98,101,114,34,58,32,34,49,34,44,32,34,114,101,108,101,97,115,101,82,101,113,117,101,115,116,77,115,103,82,101,102,34,58,32,102,97,108,115,101,44,32,34,114,101,108,101,97,115,101,68,97,116,101,34,58,32,102,97,108,115,101,44,32,34,100,105,115,112,101,110,115,101,87,105,110,100,111,119,72,105,103,104,68,97,116,101,34,58,32,34,50,48,49,57,48,57,48,54,34,44,32,34,108,105,110,101,73,116,101,109,115,34,58,32,91,123,34,115,116,97,116,117,115,34,58,32,34,48,48,48,55,34,44,32,34,109,97,120,82,101,112,101,97,116,115,34,58,32,102,97,108,115,101,44,32,34,112,114,101,118,105,111,117,115,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,73,68,34,58,32,34,48,50,69,68,55,55,55,54,45,50,49,67,68,45,52,69,55,66,45,65,67,57,68,45,68,49,68,66,70,69,69,55,66,56,67,70,34,44,32,34,111,114,100,101,114,34,58,32,49,125,44,32,123,34,115,116,97,116,117,115,34,58,32,34,48,48,48,55,34,44,32,34,109,97,120,82,101,112,101,97,116,115,34,58,32,102,97,108,115,101,44,32,34,112,114,101,118,105,111,117,115,83,116,97,116,117,115,34,58,32,102,97,108,115,101,44,32,34,73,68,34,58,32,34,52,53,68,53,70,66,49,49,45,68,55,57,51,45,52,68,53,49,45,57,65,68,68,45,57,53,69,48,70,53,52,68,50,55,56,54,34,44,32,34,111,114,100,101,114,34,58,32,50,125,93,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,83,116,97,116,117,115,34,58,32,34,48,48,48,49,34,125,125,44,32,34,83,67,78,34,58,32,50,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,34,58,32,123,34,112,114,101,115,99,114,105,112,116,105,111,110,84,121,112,101,34,58,32,34,48,48,48,49,34,44,32,34,83,67,78,34,58,32,102,97,108,115,101,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,84,114,101,97,116,109,101,110,116,84,121,112,101,34,58,32,34,48,48,48,49,34,44,32,34,115,105,103,110,101,100,84,105,109,101,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,49,34,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,77,115,103,82,101,102,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,55,51,56,53,56,50,57,95,50,68,50,69,68,70,95,49,52,54,50,57,48,50,55,54,53,34,44,32,34,112,114,101,115,99,114,105,98,105,110,103,79,114,103,97,110,105,122,97,116,105,111,110,34,58,32,34,89,57,48,51,52,55,34,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,84,105,109,101,34,58,32,34,50,48,49,56,48,57,48,54,49,54,48,48,49,49,34,44,32,34,112,101,110,100,105,110,103,67,97,110,99,101,108,108,97,116,105,111,110,115,34,58,32,102,97,108,115,101,44,32,34,117,110,115,117,99,99,101,115,115,102,117,108,67,97,110,99,101,108,108,97,116,105,111,110,115,34,58,32,102,97,108,115,101,44,32,34,104,108,55,34,58,32,123,34,101,118,101,110,116,73,68,34,58,32,34,54,66,70,52,68,69,68,56,45,56,66,49,66,45,52,69,67,54,45,57,48,51,67,45,67,54,68,66,66,56,70,53,70,51,50,57,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,84,97,114,103,101,116,82,111,108,101,34,58,32,110,117,108,108,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,82,111,108,101,34,58,32,34,83,48,48,56,48,58,71,48,52,53,48,58,82,53,48,56,48,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,80,101,114,115,111,110,34,58,32,34,71,56,52,52,56,56,55,57,34,44,32,34,97,103,101,110,116,83,121,115,116,101,109,83,68,83,49,67,111,100,101,83,121,115,116,101,109,34,58,32,34,49,46,50,46,56,50,54,46,48,46,49,50,56,53,46,48,46,50,46,48,46,49,48,55,34,44,32,34,113,117,101,114,121,83,105,122,101,34,58,32,110,117,108,108,44,32,34,102,114,111,109,65,83,73,68,34,58,32,34,50,51,48,56,49,49,50,48,49,50,52,49,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,82,111,108,101,67,111,100,101,83,121,115,116,101,109,34,58,32,110,117,108,108,44,32,34,116,111,65,83,73,68,34,58,32,34,57,57,48,49,48,49,50,51,52,53,54,55,34,44,32,34,102,105,108,101,78,97,109,101,34,58,32,110,117,108,108,44,32,34,97,103,101,110,116,83,121,115,116,101,109,83,68,83,50,34,58,32,110,117,108,108,44,32,34,97,103,101,110,116,83,121,115,116,101,109,83,68,83,49,34,58,32,34,50,51,48,56,49,49,50,48,49,50,52,49,34,44,32,34,105,115,115,117,101,87,97,114,110,105,110,103,34,58,32,110,117,108,108,44,32,34,111,114,103,73,100,34,58,32,110,117,108,108,44,32,34,109,101,115,115,97,103,101,73,68,34,58,32,34,69,70,66,53,51,48,68,50,45,66,49,69,68,45,49,49,69,56,45,65,50,57,48,45,70,48,57,50,49,67,49,48,67,53,66,53,34,44,32,34,105,110,116,101,114,97,99,116,105,111,110,73,68,34,58,32,34,80,79,82,88,95,73,78,48,50,48,49,48,49,85,75,51,49,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,82,111,108,101,80,114,111,102,105,108,101,73,100,34,58,32,34,49,48,51,49,52,50,57,57,57,57,56,57,34,44,32,34,97,103,101,110,116,80,101,114,115,111,110,83,68,83,67,111,100,101,83,121,115,116,101,109,34,58,32,110,117,108,108,44,32,34,109,101,115,115,97,103,101,86,101,114,115,105,111,110,34,58,32,34,86,51,78,80,102,73,84,52,46,50,46,48,48,34,44,32,34,111,114,105,103,105,110,97,108,70,105,108,101,78,97,109,101,34,58,32,110,117,108,108,44,32,34,97,103,101,110,116,80,101,114,115,111,110,79,114,103,67,111,100,101,34,58,32,110,117,108,108,125,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,80,114,101,115,101,110,116,34,58,32,116,114,117,101,44,32,34,112,114,101,115,99,114,105,112,116,105,111,110,73,68,34,58,32,34,69,70,56,68,67,55,45,90,70,52,66,49,69,45,49,49,69,56,65,43,34,44,32,34,109,97,120,82,101,112,101,97,116,115,34,58,32,110,117,108,108,44,32,34,99,117,114,114,101,110,116,73,110,115,116,97,110,99,101,34,58,32,34,49,34,44,32,34,100,97,121,115,83,117,112,112,108,121,34,58,32,50,56,125,44,32,34,110,111,109,105,110,97,116,105,111,110,34,58,32,123,34,110,111,109,105,110,97,116,101,100,80,101,114,102,111,114,109,101,114,84,121,112,101,34,58,32,34,80,49,34,44,32,34,110,111,109,105,110,97,116,101,100,80,101,114,102,111,114,109,101,114,34,58,32,34,70,80,50,51,48,34,44,32,34,110,111,109,105,110,97,116,101,100,34,58,32,116,114,117,101,44,32,34,110,111,109,105,110,97,116,105,111,110,72,105,115,116,111,114,121,34,58,32,91,93,125,125,106,108,0,0,0,1,104,2,109,0,0,0,8,26,182,168,146,110,67,57,69,104,2,97,1,110,5,0,17,203,5,213,14,106,104,9,100,0,4,100,105,99,116,97,1,97,16,97,16,97,8,97,80,97,48,104,16,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,104,1,104,16,106,106,106,106,106,106,106,106,106,106,106,106,106,106,108,0,0,0,1,108,0,0,0,1,100,0,5,99,108,101,97,110,100,0,4,116,114,117,101,106,106,100,0,9,117,110,100,101,102,105,110,101,100>>```

**Comment by martinsumner** [comment]
Recently leveled was refactored to allow for the functions which require application logic to be passed-in at startup, rather than have them exist within the code itself.

It would be better rather than extending the leveled code by having more knowledge of the riak_object module, to move these functions to the riak_object module (in riak_kv) and have things like v0 objects handled there.

**Comment by martinsumner** [comment]
Resolved in riak_kv for now.  Long term need to refactor Riak code out of leveled
