### ISSUE TITLE
Tags and abstraction

### ISSUE THREAD

**Issue by martinsumner** [martinsumner/leveled#32]
The use of Tags to indicate types, and the changing of behaviour by type (such as on recovery , inker compaction or penciller compaction) is a potentially powerful feature in leveled.

However, the implementation is a muddle within leveled_codec at the moment.  It is not clear what is required for a new type, and what can be done with types.

**Comment by russelldb-bet365** [comment]
I would love to look at this, for storing CRDT type things

**Comment by martinsumner** [comment]
This isn't perfect now - but https://github.com/martinsumner/leveled/pull/135 is a significant improvement.  It still isn't neatly laid out what to can be done with types, but at least the codec module is tidy, and spec'd out - and the types created by the module are exported and referenced elsewhere.

It isn't obvious how to make it a lot better easily from this point.  So will close, and open another issue if there are any other bright ideas.
