### ISSUE TITLE
EQC tests

### ISSUE THREAD

**Issue by Licenser** [martinsumner/leveled#85]
A follow-up to the discussion in #82 about using EQC to test.

**Comment by martinsumner** [comment]
Heinz, I have access to a EQC license.  I do think your idea of two levels of tests sounds like a good one.

**Comment by Licenser** [comment]
Oh nice that makes it even easyer but yes, I think the two level design has its advantages. not the least that you could let travis or something like that run the simple tests on PR's /commit)

**Comment by russelldb** [comment]
Just an update. We have a branch rdb/eqc with a basic statem for levelEd, and we are in the process of iterating on EQC tests. More to come, will keep you posted.

**Comment by martinsumner** [comment]
Forgot this issue when we added eqc tests - but there are now eqc tests, and so closing.

https://github.com/martinsumner/leveled/tree/develop-3.1/test/property
