### ISSUE TITLE
CDB backed database size ?

### ISSUE THREAD

**Issue by opensam** [martinsumner/leveled#91]
Hello,

leveled is very interesting. Pure Erlang riak-core backend ? Whaoo !
I didn't know about CDB datastores. Their page explains about 32bits adresses hence a 4Gb limit.
Does this limit apply to a whole leveled node ? or is a leveled node a growing set of several CDB files ?
Can one leveled node achieve some Tb of standalone storage ?
Can a 100ish nodes leveled powered riak-core cluster achive some Pb of cluster storage ?
Happy design and coding

**Comment by martinsumner** [comment]
Yes each individual CDB file is limited to 4GB, but the leveled store is made up of any amount of CDB files - so TB stores should be possible, although I've not tested this yet.  The CDB files are used for storing objects and are stored in sequence order, and there is a manifest maintaining the mapping between the range of sequence numbers and the individual CDB filenames.

It does mean that there is an absolute limit on object size of 4GB, although this is designed for Riak, and Riak will become unhealthy well before that limit.

**Comment by opensam** [comment]
Any amount of CDB files per store : OK, well done. Thank you for explaining.
Looking forward to reading about leveled powered big riak_core clusters (with 2i, MapReduce, etc).
